# fly.toml app configuration file generated for nodecast-tv-zsivasto on 2026-06-03T15:14:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodecast-tv-zsivasto'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'nodecast_data'
  destination = '/app/data'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
